# Generated by Django 4.1 on 2022-08-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
