# Generated by Django 4.1 on 2022-08-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_roommember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='room',
            new_name='room_name',
        ),
    ]
