# Generated by Django 4.1 on 2022-08-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_remove_room_token_remove_room_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
