# Generated by Django 4.1 on 2022-08-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_room_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='uid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
