# Generated by Django 4.1 on 2022-08-27 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_room_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='uid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
